RDKCOM-2205 RDKBCMF-268 CcspPandM ddns_broadband build failure
When the ddns_broadband DISTRO_FEATURES is observed,
the following build failure is observed:
CcspPandM/source/TR-181/middle_layer_src/cosa_dynamicdns_dml.c:1461:5: error: expected ',' or ';' before 'if'
      |     ^~
Makefile:1235: recipe for target 'libCcspPandM_middle_layer_src_la-cosa_dynamicdns_dml.lo' failed
make[4]: *** [libCcspPandM_middle_layer_src_la-cosa_dynamicdns_dml.lo] Error 1

Reason for change: RDKBCMF-268 CcspPandM ddns_broadband build failure
Test Procedure: None.
Risks: Low.
Signed-off-by: Stephen Barrett <stephen.barrett@accenture.com>

(cherry picked from commit bdd8e572b36921a585b9c1c15d12c248a40efd31)
Change-Id: I0ea72b3914465a1f85118489d401087cc5dab517