RDKCOM-3347: RDKBDEV-1273: cleanup + generalise AnscValidStringCheck()
Reason for change: Added to resolve compilation error differ in signedness .
cosa_x_cisco_com_truestaticip_dml.c:226:29: error: pointer targets in passing argument 1 of
'AnscValidStringCheck' differ in signedness [-Werror=pointer-sign]
Test Procedure: Sanity
Risks: None
Signed-off-by: SukanyaIlavarasi <sukanya.i@tataelxsi.co.in>

(cherry picked from commit 1f7658b81d08dc3066701e64067c11377b9521c6)
Change-Id: Ie0e99200384b24339f6fc48184f22cc5b826bea0