RDKCOM-1973 RDKBCMF-257 CcspPandM build errors
Build is failing in Turris platform as a result of CcspPandM/52138:
| ../../../../../../../../../../rdkb/components/opensource/ccsp/CcspPandM/source-arm/TR-181/board_sbapi/cosa_dhcpv6_apis.c:2561:5: error: 'dibblerEnabled' undeclared (first use in this function)
|   if(dibblerEnabled)
|      ^~~~~~~~~~~~~~
Plus other RPi CCspPandM build failures

Reason for change: RDKBCMF-257 CcspPandM build errors
Test Procedure: None.
Risks: Low.
Signed-off-by: Stephen Barrett <stephen.barrett@accenture.com>
(cherry picked from commit 5f38d4d809a3fa9fadf325fc24e2da8756ab9b40)
Change-Id: I92bb9fe966fcb19b809740ad18464f67f25ff4d5