RDKCOM-2280 RDKBCMF-268 CcspPandM ddns_broadband build failure
When the ddns_broadband DISTRO_FEATURES is observed,
the following build failure is observed:
| CcspPandM/source/TR-181/middle_layer_src/cosa_dslite_dml.c:660:55: error: 'DsliteTunnel' undeclared (first use in this function)
|          rc = strcpy_s(pDsliteTunnel->addr_ipv6,sizeof(DsliteTunnel->addr_ipv6), pString);
|                                                        ^
| CcspPandM/source/TR-181/middle_layer_src/cosa_dynamicdns_dml.c:59:35: error: 'pUlSize' undeclared (first use in this function)
|    59 |             rc =strcpy_s(pValue, *pUlSize, supportedServices);
|       |                                   ^~~~~~~

Reason for change: RDKBCMF-268 CcspPandM ddns_broadband build failure
Test Procedure: None.
Risks: Low.
Signed-off-by: Stephen Barrett <stephen.barrett@accenture.com>

(cherry picked from commit e64733458a3ef3b06540af7ac41ef3d145778551)
Change-Id: I2f380d8f612a1067f18a1de9a9d6fd2a3de0960b